---
title: "Capstone-Project-PD"
author: "Emma, Jasmine, Leila, Madeline"
date: "2024-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Capstone Prep

## Introduction

## Research Question(s)

## Initialization

```{r initialization}
#
# The libraries you're going to use should go here, at the very top.
# Add tidyverse. You know you're gonna use tidyverse!
# Consider a unique random seed: set.seed(ANumberThatYouHappenToLike)
#

library(tidyverse)

set.seed(0)
```

## Data Import
```{r data_import}
#
#read_csv()...
#data <- left_join(data, otherdata, by = matchingFeature)
#

parkinsons_dataset <- read_csv("../data/dataset.csv")
```

```{r data_cleaning}
# turn all - into NA DONE
parkinsons_dataset <- parkinsons_dataset %>% 
  mutate(
    across(
      everything(),
      ~ case_when(
        . == "-" ~ NA,
        TRUE ~ .
      )
    )
  )

# turn yes and no into logicals DONE
parkinsons_dataset <- parkinsons_dataset %>% 
  mutate(
    across(4,
      ~ case_when(
        . == "Yes" ~ TRUE,
        . == "No" ~ FALSE
      )
    )
  )

# turn yes and no for medication into medication name or none DONE
parkinsons_dataset <- parkinsons_dataset %>% 
  mutate(
    across(7:10,
      ~ case_when(
        substr(., 1, 3) == "Yes" ~ substr(., 7, nchar(.) - 1),
        . == "No" ~ "None"
      )
    )
  )

# turn columns into factors
parkinsons_dataset$Gender <- parkinsons_dataset$Gender %>%
  as.factor()

parkinsons_dataset[[13]] <- parkinsons_dataset[[13]] %>%
  factor(levels = c("1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5"))

parkinsons_dataset[,15:41] <- parkinsons_dataset[,15:41] %>% 
  lapply(factor, levels = 0:4)

parkinsons_dataset[, c(5, 6, 14)] <- parkinsons_dataset[, c(5, 6, 14)] %>% 
  lapply(as.numeric)

#renaming variables DONE
parkinsons_dataset <- parkinsons_dataset %>% rename(id = `Participant  code`, age = `Age  (years)`, gender = Gender, fam_history = `Positive  history  of  Parkinson  disease  in  family`, age_onset = `Age  of  disease  onset  (years)`, duration = `Duration  of  disease  from  first  symptoms  (years)`)

parkinsons_dataset <- parkinsons_dataset %>% rename(antidep_meds = `Antidepressant  therapy`, antipark_meds = `Antiparkinsonian  medication`, antipsych_meds = `Antipsychotic  medication`, benz_meds = `Benzodiazepine  medication`, ldopa = `Levodopa  equivalent  (mg/day)`, clonaz = `Clonazepam  (mg/day)`, hoen_yahr_motor = `Overview  of  motor  examination:  Hoehn  &  Yahr  scale  (-)`, updrs = `Overview  of  motor  examination:  UPDRS  III  total  (-)`, speech = `18.  Speech`, facial = `19.  Facial  Expression`, tremorRest_head = `20.  Tremor  at  Rest  -  head`, tremorRest_RUE = `20.  Tremor  at  Rest  -  RUE`, tremorRest_LUE = `20.  Tremor  at  Rest  -  LUE`, tremorRest_RLE = `20.  Tremor  at  Rest  -  RLE`, tremorRest_LLE = `20.  Tremor  at  Rest  -  LLE`, AP_tremor_RUE = `21.  Action  or  Postural  Tremor  -  RUE`, AP_tremor_LUE = `21.  Action  or  Postural  Tremor  -  LUE`, rigid_neck = `22.  Rigidity  -  neck`, rigid_RUE = `22.  Rigidity  -  RUE`, rigid_LUE = `22.  Rigidity  -  LUE`, rigid_RLE = `22.  Rigidity  -  RLE`, rigid_LLE = `22.  Rigidity  -  LLE`)

parkinsons_dataset <- parkinsons_dataset %>% rename(fingertaps_RUE = `23.Finger  Taps  -  RUE`, fingertaps_LUE = `23.Finger  Taps  -  LUE`, handmove_RUE = `24.  Hand  Movements  -  RUE`, handmove_LUE = `24.  Hand  Movements  -  LUE`, rapidAltMove_RUE = `25.  Rapid  Alternating  Movements  -  RUE`, rapidAltMove_LUE = `25.  Rapid  Alternating  Movements  -  LUE`, legAg_RLE = `26.  Leg  Agility  -  RLE`, legAG_LLE = `26.  Leg  Agility  -  LLE`, chair = `27.  Arising  from  Chair`, posture = `28.  Posture`, gait = `29.  Gait`, post_stability = `30.  Postural  Stability`, brady_hypo = `31.  Body  Bradykinesia  and  Hypokinesia`)

parkinsons_dataset <- parkinsons_dataset %>% rename(entropy1 = `Entropy  of  speech  timing  (-)...42`, rate_speech_time1 = `Rate  of  speech  timing  (-/min)...43`, accel_speech_time1 = `Acceleration  of  speech  timing  (-/min2)...44`, dur_pause_int1 = `Duration  of  pause  intervals  (ms)...45`, dur_voice_int1 = `Duration  of  voiced  intervals  (ms)...46`, gap_voiced_int1 = `Gaping  in-between  voiced  intervals  (-/min)`, dur_unvoiced_stops1 = `Duration  of  unvoiced  stops  (ms)...48`, decay_fric1 = `Decay  of  unvoiced  fricatives  (‰/min)...49`, rel_loud_resp1 = `Relative  loudness  of  respiration  (dB)...50`, pause_int_resp1 = `Pause  intervals  per  respiration  (-)...51`, rate_speech_resp1 = `Rate  of  speech  respiration  (-/min)...52`, latency_resp1 = `Latency  of  respiratory  exchange  (ms)...53`)

parkinsons_dataset <- parkinsons_dataset %>% rename(entropy2 = `Entropy  of  speech  timing  (-)...54`, rate_speech_time2 = `Rate  of  speech  timing  (-/min)...55`, accel_speech_time2 = `Acceleration  of  speech  timing  (-/min2)...56`, dur_pause_int2 = `Duration  of  pause  intervals  (ms)...57`, dur_voice_int2 = `Duration  of  voiced  intervals  (ms)...58`, gap_voiced_int2 = `Gaping  in-between  voiced  Intervals  (-/min)`, dur_unvoiced_stops2 = `Duration  of  unvoiced  stops  (ms)...60`, decay_fric2 = `Decay  of  unvoiced  fricatives  (‰/min)...61`, rel_loud_resp2 = `Relative  loudness  of  respiration  (dB)...62`, pause_int_resp2 = `Pause  intervals  per  respiration  (-)...63`, rate_speech_resp2 = `Rate  of  speech  respiration  (-/min)...64`, latency_resp2 = `Latency  of  respiratory  exchange  (ms)...65`)

```
```{r}

```
```{r}
# EDA fun
library(ggplot2)
```


```{r data_cleaning}
# turn participate code into new ID number
# create diagnosis column (HC = healthy, RBD = REM sleep disorder, PD = PD)
parkinsons_dataset<- parkinsons_dataset %>% 
  mutate(
    diagnosis = substr(id, 1, nchar(id) - 2),
    id = row_number()
  )

parkinsons_dataset$diagnosis <- parkinsons_dataset$diagnosis %>% 
  as.factor()

parkinsons_dataset <- parkinsons_dataset %>% 
  select(id, diagnosis, everything())

library(tidyverse)
glimpse(parkinsons_dataset)

ggplot(parkinsons_dataset, aes(x = speech, y = duration, color=diagnosis)) + 
         geom_jitter()

dur_rigidLLE_model <- glm(duration ~ rigid_LLE, data = parkinsons_dataset)
summary(dur_rigidLLE_model)

dur_rapidAltMove_RUE_model <- glm(duration ~ rapidAltMove_RUE, data = parkinsons_dataset)
summary(dur_rapidAltMove_RUE_model)

dur_legAg_RLE_model <- glm(duration ~ legAg_RLE, data = parkinsons_dataset)
summary(dur_legAg_RLE_model)

dur_alltremors_model <- glm(duration ~ tremorRest_head + tremorRest_RUE + tremorRest_LUE + tremorRest_LLE + tremorRest_RLE, data = parkinsons_dataset)
summary(dur_alltremors_model)

parkinsons_dataset <- parkinsons_dataset %>% 
  mutate(
    pd = case_when(
      diagnosis == "PD" ~ TRUE,
      TRUE ~ FALSE
    ),
    rbd = case_when(
      diagnosis == "RBD" ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>% 
  select(id, diagnosis, pd, rbd, everything())


ggplot(parkinsons_dataset, aes(x = pd, y = dur_pause_int1)) + 
         geom_boxplot()
model <- glm(pd ~ dur_pause_int1, family='binomial', data = parkinsons_dataset)
summary(model)

ggplot(parkinsons_dataset, aes(x = diagnosis, y = rate_speech_resp1)) + 
         geom_boxplot()


glimpse(parkinsons_dataset)

model <- glm(pd ~ entropy1 + rate_speech_time1 + accel_speech_time1 + dur_pause_int1 + dur_voice_int1 + gap_voiced_int1 + dur_unvoiced_stops1 + decay_fric1 + rel_loud_resp1 + pause_int_resp1 + rate_speech_resp1 + latency_resp1, family='binomial', data = parkinsons_dataset)
summary(model)

model <- glm(pd ~ entropy2 + rate_speech_time2 + accel_speech_time2 + dur_pause_int2 + dur_voice_int2 + gap_voiced_int2 + dur_unvoiced_stops2 + decay_fric2 + rel_loud_resp2 + pause_int_resp2 + rate_speech_resp2 + latency_resp2, family='binomial', data = parkinsons_dataset)
summary(model)

speech_all <- glm(pd ~ entropy2 + rate_speech_time2 + accel_speech_time2 + dur_pause_int2 + dur_voice_int2 + gap_voiced_int2 + dur_unvoiced_stops2 + decay_fric2 + rel_loud_resp2 + pause_int_resp2 + rate_speech_resp2 + latency_resp2 + entropy1 + rate_speech_time1 + accel_speech_time1 + dur_pause_int1 + dur_voice_int1 + gap_voiced_int1 + dur_unvoiced_stops1 + decay_fric1 + rel_loud_resp1 + pause_int_resp1 + rate_speech_resp1 + latency_resp1, family='binomial', data = parkinsons_dataset)
summary(model)

library(rsample)
library(tidyverse)
library(survival)
library(gtsummary)
library(glmnet)




set.seed(0)
data_split <- initial_split(parkinsons_dataset, prop = 0.7) 
train_data <- training(data_split)
test_data <- testing(data_split)
logistic_model2 <- glm(pd ~ entropy2 + rate_speech_time2 + accel_speech_time2 + dur_pause_int2 + dur_voice_int2 + gap_voiced_int2 + dur_unvoiced_stops2 + decay_fric2 + rel_loud_resp2 + pause_int_resp2 + rate_speech_resp2 + latency_resp2, family= binomial, data=train_data)
summary(logistic_model2)
logistic_model2 %>% tbl_regression(estimate_fun = function(x) style_number(x, digits = 3), exponentiate = TRUE)
pred_prob2 <- logistic_model2 %>% 
  predict(test_data,type="response")
predicted.classes2 <- ifelse(pred_prob2 > 0.5, TRUE, FALSE)
mean(predicted.classes2 == test_data$pd)

pred_prob_mean <- (pred_prob1 + pred_prob2) / 2
predicted_classes_mean <- ifelse(pred_prob_mean > 0.5, TRUE, FALSE)
mean(predicted_classes_mean == test_data$pd)

response_pd <-parkinsons_dataset$pd
predictors_speech1 <- data.matrix(parkinsons_dataset[, c('entropy1', 'rate_speech_time1', 'accel_speech_time1', 'dur_pause_int1', 'dur_voice_int1', 'gap_voiced_int1', 'dur_unvoiced_stops1', 'decay_fric1', 'rel_loud_resp1', 'pause_int_resp1', 'rate_speech_resp1', 'latency_resp1', 'entropy2', 'rate_speech_time2', 'accel_speech_time2', 'dur_pause_int2', 'dur_voice_int2', 'gap_voiced_int2', 'dur_unvoiced_stops2', 'decay_fric2', 'rel_loud_resp2', 'pause_int_resp2', 'rate_speech_resp2', 'latency_resp2')])
library(glmnet)
cv_model <- cv.glmnet(predictors_speech1, response_pd, alpha = 1)
best_lambda <- cv_model$lambda.min
best_lambda
plot(cv_model)
best_model <- glmnet(predictors_speech1, response_pd, alpha = 1, lambda = best_lambda)
coef(best_model)

#According to Lasso Test the important varibales are:
#rate_speech_time1   -0.0001383232
#dur_pause_int1       0.0002775279
#dur_pause_int2       0.0004353519

library(rsample)
library(tidyverse)
library(survival)
library(gtsummary)
library(glmnet)
set.seed(0)
data_split <- initial_split(parkinsons_dataset, prop = 0.7) 
train_data <- training(data_split)
test_data <- testing(data_split)
logistic_model2 <- glm(pd ~ rate_speech_time1 + dur_pause_int1 + dur_pause_int2, family= binomial, data=train_data)
summary(logistic_model2)
logistic_model2 %>% tbl_regression(estimate_fun = function(x) style_number(x, digits = 3), exponentiate = TRUE)
pred_prob2 <- logistic_model2 %>% 
  predict(test_data,type="response")
predicted.classes2 <- ifelse(pred_prob2 > 0.5, TRUE, FALSE)
mean(predicted.classes2 == test_data$pd)

#dur pause 1
ggplot(parkinsons_dataset, aes(x = dur_pause_int1, y = pd, color = pd)) + 
         geom_boxplot() +
  stat_summary(fun.y = "mean", geom = "point", shape = 18, size = 3, color = "navyblue") +
  scale_color_manual(values = c("deepskyblue","orange"), labels = c("TRUE" = "PD", "FALSE" = "No PD")) +
         scale_y_discrete(labels = c("TRUE" = "PD", "FALSE" = "No PD")) +
         labs(x = "Duration of Pause Intervals from Reading (ms)", y = "Status of Parkinson's Disease",  title = "Reading DPI of Patients with PD Compared to those without PD", , color = NULL) +
  theme_bw()

# dur pause 2
ggplot(parkinsons_dataset, aes(x = dur_pause_int2, y = pd, color = pd)) + 
         geom_boxplot() +
  stat_summary(fun.y = "mean", geom = "point", shape = 18, size = 3, color = "navyblue") +
  scale_color_manual(values = c("deepskyblue","orange"), labels = c("TRUE" = "PD", "FALSE" = "No PD")) +
  scale_y_discrete(labels = c("TRUE" = "PD", "FALSE" = "No PD")) +
         labs(x = "Duration of Pause Intervals from Monologue (ms)", y = "Status of Parkinson's Disease",  title = "Monologue DPI of Patients with PD Compared to those without PD", color = NULL) +
  theme_bw()

# rate_speech_time1
ggplot(parkinsons_dataset, aes(x = rate_speech_time1, y = pd, color = pd)) + 
         geom_boxplot() +
  stat_summary(fun.y = "mean", geom = "point", shape = 18, size = 3, color = "navyblue") +
  scale_color_manual(values = c("deepskyblue","orange"), labels = c("TRUE" = "PD", "FALSE" = "No PD")) +
         scale_y_discrete(labels = c("TRUE" = "PD", "FALSE" = "No PD")) +
         labs(x = "Rate of Speech Timing from Reading", y = "Status of Parkinson's Disease",  title = "Reading RST of Patients with PD Compared to those without PD", color = NULL) +
  theme_bw()


```

## Exploratory Data Analysis

## Models and Statistical Tests

## Results

## Conclusions